sudo: required

dist: 
- focal
- trusty

language: c

compiler: gcc

branches:
  only:
  - master
before_install:
- sudo apt-get install libphp5-embed php5-dev autoconf automake gcc make libpcre3-dev libdb5.1-dev libbz2-dev libbz2-dev libxml2-dev libkrb5-dev php5-dev
#- wget --content-disposition "http://sourceforge.net/projects/zabbix/files/ZABBIX%20Latest%20Stable/3.2.1/zabbix-3.2.1.tar.gz/download"
#- tar xzvf zabbix-3.2.1.tar.gz
#- cd zabbix-3.2.1
- wget --content-disposition "https://sourceforge.net/projects/zabbix/files/latest/download?source=files"
- tar xzvf zabbix*.tar.gz
- cd zabbix*
- ./configure
- cd -
- ./bootstrap.sh

install: 
- export ZABBIX_PATH=$(cd zabbix*;pwd)
- PATH=/usr/bin:$PATH ./configure --prefix=/home/ubuntu/src/github.com/ZenProjects/test --with-php=/usr  --with-zabbix-include=$ZABBIX_PATH/include  
script:
- make
