sudo: required

dist: 
- focal
- trusty

language: c

compiler: gcc

branches:
  only:
  - master
  
before_install:
- if [ "$TRAVIS_DIST" = "trusty" ]; then sudo apt-get install libphp5-embed php5-dev autoconf automake gcc make libpcre3-dev libbz2-dev libbz2-dev libxml2-dev libkrb5-dev; fi
- if [ "$TRAVIS_DIST" = "focal" ]; then sudo apt-get install libphp-embed php-dev autoconf automake gcc make libpcre3-dev libbz2-dev libbz2-dev libxml2-dev libkrb5-dev; fi

- rm -f zabbix*
- if [ "$TRAVIS_DIST" = "trusty" ]; then wget --content-disposition "https://cdn.zabbix.com/zabbix/sources/stable/4.0/zabbix-4.0.28.tar.gz"; fi
- if [ "$TRAVIS_DIST" = "focal" ]; then wget --content-disposition "https://cdn.zabbix.com/zabbix/sources/stable/5.0/zabbix-5.0.8.tar.gz"; fi
- tar xzvf zabbix*.tar.gz
- cd zabbix*/
- find /usr/lib /lib -name "libphp*so*"
- ./configure
- cd -
- ./bootstrap.sh

install: 
- export ZABBIX_PATH=$(cd zabbix*;pwd)
- PATH=/usr/bin:$PATH ./configure --prefix=/home/ubuntu/src/github.com/ZenProjects/test --with-php=/usr  --with-zabbix-include=$ZABBIX_PATH/include  || cat config.log

script:
- make
