sudo: required

matrix:
    include:
        - dist: trusty
        - dist: focal

language: c

compiler: gcc

branches:
  only:
  - master
  
before_install:
- if [ "$TRAVIS_DIST" = "trusty" ]; then sudo apt-get install libphp5-embed php5-dev autoconf automake gcc make libpcre3-dev libbz2-dev libbz2-dev libxml2-dev libkrb5-dev libdb5.3-dev; fi
- if [ "$TRAVIS_DIST" = "trusty" ]; then sudo sed -ie "s#uint _res:31#uint res:31#" /usr/include/php5/main/php_output.h; fi
- if [ "$TRAVIS_DIST" = "focal" ]; then sudo apt-get install libphp-embed php-dev autoconf automake gcc make libpcre3-dev libbz2-dev libbz2-dev libxml2-dev libkrb5-dev libargon2-dev libargon2-1 libargon2-0 libsodium-dev; fi
- find /usr/lib /lib -name "libphp*so*"
- cat /home/travis/.phpenv/version

- rm -f zabbix*
- if [ "$TRAVIS_DIST" = "trusty" ]; then wget --content-disposition "https://cdn.zabbix.com/zabbix/sources/stable/4.0/zabbix-4.0.28.tar.gz"; fi
- if [ "$TRAVIS_DIST" = "focal" ]; then wget --content-disposition "https://cdn.zabbix.com/zabbix/sources/stable/5.0/zabbix-5.0.8.tar.gz"; fi
- tar xzvf zabbix*.tar.gz
- cd zabbix*/
- export ZABBIX_PATH=$PWD
- ./configure
- cd -
- ./bootstrap.sh

install: 
- if [ "$TRAVIS_DIST" = "trusty" ]; then CFLAGS="-w" PATH=/usr/bin:$PATH ./configure --prefix=/home/ubuntu/src/github.com/ZenProjects/test --with-php=/usr  --with-zabbix-include=$ZABBIX_PATH/include  || (cat config.log;exit 1); fi
- if [ "$TRAVIS_DIST" = "focal" ]; then PATH=/usr/bin:$PATH ./configure --prefix=/home/ubuntu/src/github.com/ZenProjects/test --with-php=/usr  --with-zabbix-include=$ZABBIX_PATH/include  || (cat config.log;exit 1); fi

script:
- make
